{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "userlocationapi.serviceAccountName" . }}
  labels:
    {{- include "userlocationapi.labels" . | nindent 4 }}
{{- end -}}
