{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "userlocationapi.fullname" . }}
  labels:
    {{- include "userlocationapi.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: http
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      app: {{ template "userlocationapi.fullname" . }}
{{- end }}
